import yaml from "js-yaml";
import { z } from "zod";
import type { DrumPattern, GrooveSpec, InstrumentName, NoteEvent, Section, SongMeta, Track } from "../types";
import { parseSongMetaYaml, parseTrackYaml } from "./songSchema";

export const generatedHeader = "# Generated by `bun run arrange compile`. Edit arrangement.ts or arrangement.yaml, then recompile.\n";

const instrumentIds = [
  "grand_piano",
  "cinematic_strings",
  "upright_bass",
  "hybrid_drums",
  "drum_kit",
  "glass_pad",
  "solo_cello",
  "analog_lead",
  "electric_piano"
] as const;

const timeValue = z.union([z.string().min(1), z.number().nonnegative()]);
const pitchValue = z.union([z.string().min(1), z.number()]);
const automationPointSchema = z.object({ time: timeValue, value: z.number() });
const automationSchema = z
  .object({
    gain: z.array(automationPointSchema).optional(),
    filter: z.array(automationPointSchema).optional(),
    reverb: z.array(automationPointSchema).optional(),
    pan: z.array(automationPointSchema).optional()
  })
  .optional();

const noteSchema = z.object({
  time: timeValue,
  duration: timeValue,
  pitch: pitchValue.optional(),
  pitches: z.array(pitchValue).optional(),
  velocity: z.number().min(0).max(1).optional(),
  articulation: z.enum(["legato", "staccato", "marcato", "sustain", "pluck"]).optional(),
  offset: z.number().min(-0.25).max(0.25).optional(),
  strum: z.number().min(0).max(0.25).optional(),
  ghost: z.boolean().optional(),
  flam: z.number().min(0).max(0.05).optional(),
  gain: z.number().min(0).max(2).optional()
});

const soundSchema = z.object({
  source: z.enum(["soundfont", "sample_pack", "fallback"]).optional(),
  soundfont: z.string().min(1).optional(),
  samplePack: z.string().min(1).optional(),
  attack: z.number().min(0).max(5).optional(),
  decay: z.number().min(0).max(5).optional(),
  sustain: z.number().min(0).max(1).optional(),
  release: z.number().min(0).max(8).optional()
});

const kitVoiceSchema = z.object({
  soundfont: z.string().min(1).optional(),
  pitch: pitchValue.optional(),
  gain: z.number().min(0).max(2).optional()
});

const patternSchema = z.object({
  resolution: z.number().int().min(2).max(64).optional(),
  bars: z.number().int().min(1).max(64).optional(),
  repeat: z.number().int().min(1).max(64).optional(),
  start: timeValue.optional(),
  swing: z.number().min(0).max(0.4).optional(),
  velocity: z
    .object({
      default: z.number().min(0).max(1).optional(),
      ghost: z.number().min(0).max(1).optional(),
      accent: z.number().min(0).max(1).optional()
    })
    .optional(),
  lanes: z.record(z.string().min(1), z.string())
});

const grooveSchema = z.object({
  resolution: z.number().int().min(2).max(64).optional(),
  offsets: z.array(z.number().min(-200).max(200)).min(1)
});

const eqSchema = z.object({
  lowGain: z.number().min(-24).max(24).optional(),
  lowFrequency: z.number().min(20).max(2000).optional(),
  midGain: z.number().min(-24).max(24).optional(),
  midFrequency: z.number().min(80).max(12000).optional(),
  midQ: z.number().min(0.1).max(18).optional(),
  highGain: z.number().min(-24).max(24).optional(),
  highFrequency: z.number().min(1000).max(20000).optional()
});

const compressorSchema = z.object({
  threshold: z.number().min(-80).max(0).optional(),
  knee: z.number().min(0).max(40).optional(),
  ratio: z.number().min(1).max(30).optional(),
  attack: z.number().min(0).max(1).optional(),
  release: z.number().min(0.01).max(3).optional(),
  makeupGain: z.number().min(0).max(4).optional()
});

const mixSchema = z.object({
  gain: z.number().min(0).max(2).optional(),
  pan: z.number().min(-1).max(1).optional(),
  reverb: z.number().min(0).max(1).optional(),
  delay: z.number().min(0).max(1).optional(),
  delayTime: z.number().min(0.02).max(2).optional(),
  delayFeedback: z.number().min(0).max(0.85).optional(),
  saturation: z.number().min(0).max(1).optional(),
  lowpass: z.number().min(40).max(20000).optional(),
  highpass: z.number().min(20).max(8000).optional(),
  duck: z.string().min(1).optional(),
  duckAmount: z.number().min(0).max(1).optional(),
  eq: eqSchema.optional(),
  compressor: compressorSchema.optional(),
  automation: automationSchema
});

const performanceSchema = z.object({
  humanize: z.number().min(0).max(0.08).optional(),
  swing: z.number().min(0).max(0.35).optional(),
  velocity: z.number().min(0).max(1).optional(),
  velocityRamp: z.tuple([z.number().min(0).max(1), z.number().min(0).max(1)]).optional(),
  strum: z.number().min(0).max(0.25).optional(),
  articulation: z.enum(["legato", "staccato", "marcato", "sustain", "pluck"]).optional(),
  octave: z.number().int().min(-3).max(3).optional()
});

const motifNoteSchema = z.object({
  degree: z.number().int().min(-14).max(21),
  octave: z.number().int().min(1).max(7).optional(),
  step: z.number().min(0).optional(),
  duration: timeValue.optional(),
  velocity: z.number().min(0).max(1).optional(),
  gain: z.number().min(0).max(2).optional(),
  articulation: z.enum(["legato", "staccato", "marcato", "sustain", "pluck"]).optional()
});

const motifSchema = z.object({
  notes: z.array(motifNoteSchema).min(1)
});

const sectionSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  start: timeValue,
  duration: timeValue,
  scene: z.enum(["aurora", "cathedral", "tunnel", "nebula"]),
  intensity: z.number().min(0).max(2).optional()
});

const harmonyPointSchema = z.object({
  time: timeValue,
  duration: timeValue.optional(),
  chord: z.string().min(1)
});

const voicingSchema = z.object({
  range: z.string().regex(/^[A-G](?:#|b)?-?\d-[A-G](?:#|b)?-?\d$/).optional(),
  maxVoices: z.number().int().min(2).max(6).optional(),
  inversion: z.number().int().min(0).max(4).optional(),
  spread: z.boolean().optional()
});

const partSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1).optional(),
  role: z.enum(["drums", "bass", "harmony", "lead", "counterline", "texture", "pad", "ear_candy", "custom"]),
  intent: z.string().min(1).optional(),
  instrument: z.enum(instrumentIds).optional(),
  sections: z.array(z.string().min(1)).optional(),
  sound: soundSchema.optional(),
  kit: z.record(z.string().min(1), kitVoiceSchema).optional(),
  pattern: patternSchema.optional(),
  groove: z.union([z.string().min(1), grooveSchema]).optional(),
  mix: mixSchema.optional(),
  performance: performanceSchema.optional(),
  voicing: voicingSchema.optional(),
  motif: z.string().min(1).optional(),
  motifPlacement: z.enum(["sections", "harmony"]).optional(),
  bassStyle: z.enum(["roots", "pulse", "walking"]).optional(),
  fills: z.boolean().optional(),
  notes: z.array(noteSchema).optional()
});

const arrangementSchema = z.object({
  title: z.string().min(1),
  artist: z.string().optional(),
  tempo: z.number().min(30).max(240),
  tempoMap: z.array(z.object({ time: timeValue, bpm: z.number().min(20).max(320) })).optional(),
  key: z.string().min(1),
  timeSignature: z.string().regex(/^\d+\/\d+$/),
  master: z
    .object({
      gain: z.number().min(0).max(1.2).optional(),
      limiter: z.boolean().optional(),
      vinyl: z.number().min(0).max(1).optional(),
      reverbIrSeconds: z.number().min(0.3).max(8).optional(),
      reverbIrDecay: z.number().min(0.5).max(6).optional(),
      reverbReturnGain: z.number().min(0).max(1).optional()
    })
    .optional(),
  sections: z.array(sectionSchema).min(1),
  harmony: z.array(harmonyPointSchema).min(1),
  motifs: z.record(z.string().min(1), motifSchema).optional(),
  grooves: z.record(z.string().min(1), grooveSchema).optional(),
  parts: z.array(partSchema).min(1)
});

export type ArrangementDocument = z.infer<typeof arrangementSchema>;
export type ArrangementSourceRef = {
  part: string;
  role: z.infer<typeof partSchema>["role"];
  intent?: string;
  generator: "explicit" | "harmony" | "bass" | "motif" | "ear_candy" | "fill" | "pattern";
  harmonyIndex?: number;
  chord?: string;
  motif?: string;
  motifIndex?: number;
  placementIndex?: number;
  section?: string;
};
export type ArrangementSourceMap = {
  version: 1;
  tracks: Record<
    string,
    {
      part: string;
      role: z.infer<typeof partSchema>["role"];
      intent?: string;
      pattern?: ArrangementSourceRef;
      notes: Array<ArrangementSourceRef & { index: number; time: string | number; pitch?: string | number; pitches?: Array<string | number> }>;
    }
  >;
};
export type CompiledArrangement = {
  song: SongMeta;
  tracks: Track[];
  warnings: string[];
  sourceMap: ArrangementSourceMap;
};

type HarmonyPoint = z.infer<typeof harmonyPointSchema> & { duration: string | number };
type GeneratedNote = {
  note: NoteEvent;
  source: ArrangementSourceRef;
};

const pitchClasses: Record<string, number> = {
  C: 0,
  "C#": 1,
  Db: 1,
  D: 2,
  "D#": 3,
  Eb: 3,
  E: 4,
  F: 5,
  "F#": 6,
  Gb: 6,
  G: 7,
  "G#": 8,
  Ab: 8,
  A: 9,
  "A#": 10,
  Bb: 10,
  B: 11
};
const sharpNames = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
const majorScale = [0, 2, 4, 5, 7, 9, 11];
const minorScale = [0, 2, 3, 5, 7, 8, 10];

export function parseArrangementYaml(source: string): ArrangementDocument {
  const loaded = yaml.load(source);
  const parsed = arrangementSchema.safeParse(loaded);
  if (!parsed.success) {
    throw new Error(parsed.error.issues.map((issue) => `${issue.path.join(".") || "arrangement"}: ${issue.message}`).join("\n"));
  }
  return parsed.data;
}

export function compileArrangementYaml(source: string): CompiledArrangement {
  return compileArrangement(parseArrangementYaml(source));
}

export function compileArrangement(source: ArrangementDocument): CompiledArrangement {
  const arrangement = arrangementSchema.parse(source);
  const song: SongMeta = {
    title: arrangement.title,
    artist: arrangement.artist,
    tempo: arrangement.tempo,
    tempoMap: arrangement.tempoMap,
    key: arrangement.key,
    timeSignature: arrangement.timeSignature,
    master: {
      gain: arrangement.master?.gain ?? 0.82,
      limiter: arrangement.master?.limiter ?? true,
      vinyl: arrangement.master?.vinyl,
      reverbIrSeconds: arrangement.master?.reverbIrSeconds,
      reverbIrDecay: arrangement.master?.reverbIrDecay,
      reverbReturnGain: arrangement.master?.reverbReturnGain
    },
    sections: arrangement.sections as Section[],
    trackOrder: arrangement.parts.map((part) => part.id)
  };

  const measures = beatsPerMeasure(song.timeSignature);
  const harmony = normalizeHarmony(arrangement.harmony, measures);
  const warnings: string[] = [];
  const compiledParts = arrangement.parts.map((part) => compilePart(part, arrangement, song, harmony, warnings));
  const tracks = compiledParts.map((part) => part.track);
  const sourceMap: ArrangementSourceMap = {
    version: 1,
    tracks: Object.fromEntries(compiledParts.map((part) => [part.track.id, part.source]))
  };

  parseSongMetaYaml(dumpYaml(song));
  for (const track of tracks) parseTrackYaml(dumpYaml(track));

  return { song: prune(song), tracks: tracks.map((track) => prune(track)), warnings, sourceMap: prune(sourceMap) };
}

export function serializeSong(song: SongMeta): string {
  return generatedHeader + dumpYaml(prune(song));
}

export function serializeTrack(track: Track): string {
  return generatedHeader + dumpYaml(prune(track));
}

export function serializeSourceMap(sourceMap: ArrangementSourceMap): string {
  return `${JSON.stringify(prune(sourceMap), null, 2)}\n`;
}

function compilePart(
  part: z.infer<typeof partSchema>,
  arrangement: ArrangementDocument,
  song: SongMeta,
  harmony: HarmonyPoint[],
  warnings: string[]
): { track: Track; source: ArrangementSourceMap["tracks"][string] } {
  const generated = (part.notes ?? []).map((note) => ({
    note: note as NoteEvent,
    source: noteSource(part, "explicit")
  })) satisfies GeneratedNote[];
  const performance = part.performance ?? {};
  const role = part.role;

  if (role === "harmony" || role === "pad" || role === "texture") {
    generated.push(...compileChordPart(part, song, harmony));
  } else if (role === "bass") {
    generated.push(...compileBassPart(part, song, harmony));
  } else if (role === "lead" || role === "counterline") {
    generated.push(...compileMotifPart(part, arrangement, song, harmony, warnings));
  } else if (role === "ear_candy") {
    generated.push(...compileEarCandy(part, song));
  }

  if (role === "drums" && part.fills !== false) {
    generated.push(...compileDrumFills(part, song));
  }

  const sortedGenerated = sortGeneratedNotes(shapeGeneratedVelocities(generated, performance.velocityRamp));
  const track: Track = {
    id: part.id,
    name: part.name ?? titleFromId(part.id),
    role,
    instrument: part.instrument ?? defaultInstrument(role),
    sound: part.sound,
    kit: part.kit,
    pattern: part.pattern as DrumPattern | undefined,
    groove: resolveGroove(part.groove, arrangement.grooves),
    ...part.mix,
    humanize: performance.humanize,
    swing: performance.swing,
    octave: performance.octave,
    notes: sortedGenerated.map((entry) => entry.note)
  };
  return {
    track,
    source: {
      part: part.id,
      role: part.role,
      intent: part.intent,
      pattern: part.pattern ? noteSource(part, "pattern") : undefined,
      notes: sortedGenerated.map((entry, index) => ({
        ...entry.source,
        index,
        time: entry.note.time,
        pitch: entry.note.pitch,
        pitches: entry.note.pitches
      }))
    }
  };
}

function compileChordPart(part: z.infer<typeof partSchema>, song: SongMeta, harmony: HarmonyPoint[]): GeneratedNote[] {
  const role = part.role;
  const performance = part.performance ?? {};
  const durationFallback = role === "texture" || role === "pad" ? "4m" : "1m";
  return harmony
    .map((point, index) => ({ point, index }))
    .filter(({ point }) => isPointActive(point.time, part.sections, song.sections, song.timeSignature))
    .map(({ point, index }) => {
      const chord = parseChord(point.chord);
      const pitches = voiceChord(chord.root, chord.intervals, part.voicing, role);
      const velocityBase = performance.velocity ?? (role === "harmony" ? 0.48 : 0.32);
      return {
        note: {
          time: point.time,
          duration: point.duration ?? durationFallback,
          pitches,
          velocity: clamp(velocityBase + sectionLift(index) * 0.05, 0.18, 0.82),
          articulation: performance.articulation ?? "sustain",
          strum: performance.strum ?? (role === "harmony" ? 0.014 : 0.04)
        },
        source: {
          ...noteSource(part, "harmony"),
          harmonyIndex: index,
          chord: point.chord,
          section: sectionAtTime(point.time, song.sections, song.timeSignature)
        }
      };
    });
}

function compileBassPart(part: z.infer<typeof partSchema>, song: SongMeta, harmony: HarmonyPoint[]): GeneratedNote[] {
  const measures = beatsPerMeasure(song.timeSignature);
  const style = part.bassStyle ?? "pulse";
  const velocity = part.performance?.velocity ?? 0.62;
  const octave = part.performance?.octave ?? -1;
  const notes: GeneratedNote[] = [];

  harmony.forEach((point, index) => {
    if (!isPointActive(point.time, part.sections, song.sections, song.timeSignature)) return;
    const chord = parseChord(point.chord);
    const root = midiToPitch(rootMidi(chord.root, 2 + octave));
    const startBeat = toBeats(point.time, measures);
    const durBeats = durationToBeats(point.duration, measures);
    const fifth = midiToPitch(rootMidi(chord.root, 2 + octave) + 7);

    const baseSource = {
      ...noteSource(part, "bass"),
      harmonyIndex: index,
      chord: point.chord,
      section: sectionAtTime(point.time, song.sections, song.timeSignature)
    };

    notes.push({ note: { time: point.time, duration: style === "roots" ? point.duration : "2n", pitch: root, velocity, articulation: "pluck" }, source: baseSource });
    if (style !== "roots" && durBeats >= 2) {
      notes.push({ note: { time: beatsToTime(startBeat + 2, measures), duration: "4n", pitch: fifth, velocity: velocity * 0.78, articulation: "pluck" }, source: baseSource });
    }
    if (style === "walking" && durBeats >= 4) {
      const next = harmony[(index + 1) % harmony.length];
      const nextRoot = parseChord(next.chord).root;
      const approach = approachPitch(rootMidi(chord.root, 2 + octave), rootMidi(nextRoot, 2 + octave));
      notes.push({ note: { time: beatsToTime(startBeat + 3.5, measures), duration: "8n", pitch: midiToPitch(approach), velocity: velocity * 0.72, articulation: "pluck" }, source: baseSource });
    }
  });

  return notes;
}

function compileMotifPart(
  part: z.infer<typeof partSchema>,
  arrangement: ArrangementDocument,
  song: SongMeta,
  harmony: HarmonyPoint[],
  warnings: string[]
): GeneratedNote[] {
  const motifId = part.motif;
  if (!motifId) return [];
  const motif = arrangement.motifs?.[motifId];
  if (!motif) {
    warnings.push(`${part.id}: motif "${motifId}" was not found`);
    return [];
  }

  const measures = beatsPerMeasure(song.timeSignature);
  const starts = part.motifPlacement === "harmony" ? harmony.map((point) => point.time) : song.sections.map((section) => section.start);
  const velocity = part.performance?.velocity ?? (part.role === "lead" ? 0.54 : 0.42);
  const degreeOffsets = [0, 1, -1, 2, -2];
  const notes: GeneratedNote[] = [];

  starts.forEach((start, placementIndex) => {
    if (!isPointActive(start, part.sections, song.sections, song.timeSignature)) return;
    const base = toBeats(start, measures);
    let cursor = 0;
    for (const [motifIndex, motifNote] of motif.notes.entries()) {
      const step = motifNote.step ?? cursor;
      const pitch = degreeToPitch(
        song.key,
        motifNote.degree + degreeOffsets[placementIndex % degreeOffsets.length],
        motifNote.octave ?? (part.role === "lead" ? 5 : 4)
      );
      const duration = motifNote.duration ?? "8n";
      notes.push({
        note: {
          time: beatsToTime(base + step, measures),
          duration,
          pitch,
          velocity: motifNote.velocity ?? clamp(velocity + sectionLift(placementIndex) * 0.06, 0.18, 0.88),
          articulation: motifNote.articulation ?? part.performance?.articulation ?? "legato",
          gain: motifNote.gain
        },
        source: {
          ...noteSource(part, "motif"),
          motif: motifId,
          motifIndex,
          placementIndex,
          section: sectionAtTime(start, song.sections, song.timeSignature)
        }
      });
      cursor = step + durationToBeats(duration, measures);
    }
  });

  return notes;
}

function compileEarCandy(part: z.infer<typeof partSchema>, song: SongMeta): GeneratedNote[] {
  const measures = beatsPerMeasure(song.timeSignature);
  const velocity = part.performance?.velocity ?? 0.34;
  return song.sections.slice(1).flatMap((section, index) => {
    if (!isPointActive(section.start, part.sections, song.sections, song.timeSignature)) return [];
    const startBeat = Math.max(0, toBeats(section.start, measures) - 0.5);
    const octave = index % 2 === 0 ? 5 : 6;
    const source = { ...noteSource(part, "ear_candy"), placementIndex: index, section: section.id };
    return [
      { note: { time: beatsToTime(startBeat, measures), duration: "8n", pitch: `C${octave}`, velocity, articulation: "staccato" }, source },
      { note: { time: beatsToTime(startBeat + 0.25, measures), duration: "8n", pitch: `Eb${octave}`, velocity: velocity * 0.86, articulation: "staccato" }, source }
    ];
  });
}

function compileDrumFills(part: z.infer<typeof partSchema>, song: SongMeta): GeneratedNote[] {
  const measures = beatsPerMeasure(song.timeSignature);
  return song.sections.slice(1).flatMap((section) => {
    const start = toBeats(section.start, measures);
    const source = { ...noteSource(part, "fill"), section: section.id };
    return [
      { note: { time: beatsToTime(Math.max(0, start - 0.5), measures), duration: "8n", pitch: "snare", velocity: 0.62, flam: 0.018 }, source },
      { note: { time: beatsToTime(Math.max(0, start - 0.25), measures), duration: "8n", pitch: "open_hat", velocity: 0.52 }, source }
    ];
  });
}

function normalizeHarmony(points: z.infer<typeof harmonyPointSchema>[], measures: number): HarmonyPoint[] {
  return points.map((point, index) => {
    const next = points[index + 1];
    const duration = point.duration ?? (next ? beatsToDuration(toBeats(next.time, measures) - toBeats(point.time, measures), measures) : "1m");
    return { ...point, duration };
  });
}

function resolveGroove(value: z.infer<typeof partSchema>["groove"], grooves: ArrangementDocument["grooves"]): GrooveSpec | undefined {
  if (!value) return undefined;
  if (typeof value !== "string") return value;
  const groove = grooves?.[value];
  if (!groove) throw new Error(`Unknown groove: ${value}`);
  return groove;
}

function noteSource(part: z.infer<typeof partSchema>, generator: ArrangementSourceRef["generator"]): ArrangementSourceRef {
  return {
    part: part.id,
    role: part.role,
    intent: part.intent,
    generator
  };
}

function shapeGeneratedVelocities(notes: GeneratedNote[], ramp?: [number, number]): GeneratedNote[] {
  if (!ramp || notes.length < 2) return notes;
  return notes.map((entry, index) => {
    const t = index / Math.max(1, notes.length - 1);
    const shaped = ramp[0] + (ramp[1] - ramp[0]) * t;
    const accent = entry.note.velocity === undefined ? 0 : (entry.note.velocity - 0.5) * 0.18;
    return {
      ...entry,
      note: {
        ...entry.note,
        velocity: clamp(shaped + accent, 0, 1)
      }
    };
  });
}

function sortGeneratedNotes(notes: GeneratedNote[]): GeneratedNote[] {
  return [...notes].sort((a, b) => String(a.note.time).localeCompare(String(b.note.time), undefined, { numeric: true }));
}

function shapeVelocities(notes: NoteEvent[], ramp?: [number, number]): NoteEvent[] {
  if (!ramp || notes.length < 2) return notes;
  return notes.map((note, index) => {
    const t = index / Math.max(1, notes.length - 1);
    const shaped = ramp[0] + (ramp[1] - ramp[0]) * t;
    const accent = note.velocity === undefined ? 0 : (note.velocity - 0.5) * 0.18;
    return { ...note, velocity: clamp(shaped + accent, 0, 1) };
  });
}

function sortNotes(notes: NoteEvent[]): NoteEvent[] {
  return [...notes].sort((a, b) => String(a.time).localeCompare(String(b.time), undefined, { numeric: true }));
}

function isPointActive(time: string | number, sectionIds: string[] | undefined, sections: Section[], timeSignature: string): boolean {
  if (!sectionIds?.length) return true;
  const measures = beatsPerMeasure(timeSignature);
  const beat = toBeats(time, measures);
  return sections.some((section) => {
    if (!sectionIds.includes(section.id)) return false;
    const start = toBeats(section.start, measures);
    const end = start + durationToBeats(section.duration, measures);
    return beat >= start && beat < end;
  });
}

function sectionAtTime(time: string | number, sections: Section[], timeSignature: string): string | undefined {
  const measures = beatsPerMeasure(timeSignature);
  const beat = toBeats(time, measures);
  return sections.find((section) => {
    const start = toBeats(section.start, measures);
    const end = start + durationToBeats(section.duration, measures);
    return beat >= start && beat < end;
  })?.id;
}

function parseChord(symbol: string): { root: string; intervals: number[] } {
  const [chord] = symbol.split("/");
  const match = chord.match(/^([A-G](?:#|b)?)(.*)$/);
  if (!match) throw new Error(`Unsupported chord: ${symbol}`);
  const root = match[1];
  const quality = match[2].toLowerCase();

  if (quality.includes("dim")) return { root, intervals: [0, 3, 6] };
  if (quality.includes("sus2")) return { root, intervals: [0, 2, 7] };
  if (quality.includes("sus")) return { root, intervals: [0, 5, 7] };
  if (quality.includes("m9") || quality.includes("min9")) return { root, intervals: [0, 3, 7, 10, 14] };
  if (quality.includes("m7") || quality.includes("min7") || quality.includes("-7")) return { root, intervals: [0, 3, 7, 10] };
  if (quality === "m" || quality.includes("min") || quality.startsWith("-")) return { root, intervals: [0, 3, 7] };
  if (quality.includes("add9")) return { root, intervals: [0, 4, 7, 14] };
  if (quality.includes("maj9")) return { root, intervals: [0, 4, 7, 11, 14] };
  if (quality.includes("maj7") || quality.includes("ma7")) return { root, intervals: [0, 4, 7, 11] };
  if (quality.includes("13")) return { root, intervals: [0, 4, 7, 10, 14, 21] };
  if (quality.includes("9")) return { root, intervals: [0, 4, 7, 10, 14] };
  if (quality.includes("7")) return { root, intervals: [0, 4, 7, 10] };
  if (quality.includes("6")) return { root, intervals: [0, 4, 7, 9] };
  return { root, intervals: [0, 4, 7] };
}

function voiceChord(root: string, intervals: number[], voicing: z.infer<typeof voicingSchema> | undefined, role: string): string[] {
  const range = voicing?.range ? parseRange(voicing.range) : role === "harmony" ? [48, 76] : [55, 84];
  const maxVoices = voicing?.maxVoices ?? (role === "harmony" ? 4 : 5);
  let midis = intervals.slice(0, maxVoices).map((interval) => rootMidi(root, 3) + interval);
  midis = midis.map((midi) => placeInRange(midi, range[0], range[1]));
  midis.sort((a, b) => a - b);

  for (let i = 0; i < (voicing?.inversion ?? 0); i += 1) {
    const first = midis.shift();
    if (first !== undefined) midis.push(placeInRange(first + 12, range[0], range[1]));
    midis.sort((a, b) => a - b);
  }

  if (voicing?.spread) {
    midis = midis.map((midi, index) => (index % 2 === 1 ? placeInRange(midi + 12, range[0], range[1]) : midi));
    midis.sort((a, b) => a - b);
  }

  return Array.from(new Set(midis)).map(midiToPitch);
}

function degreeToPitch(key: string, degree: number, octave: number): string {
  const match = key.match(/^([A-G](?:#|b)?)\s+(major|minor)$/i);
  const tonic = match ? pitchClasses[match[1]] ?? 0 : 0;
  const scale = match?.[2].toLowerCase() === "major" ? majorScale : minorScale;
  const zeroBased = degree - 1;
  const octaveShift = Math.floor(zeroBased / scale.length);
  const index = ((zeroBased % scale.length) + scale.length) % scale.length;
  const midi = (octave + 1 + octaveShift) * 12 + tonic + scale[index];
  return midiToPitch(midi);
}

function rootMidi(root: string, octave: number): number {
  const pitchClass = pitchClasses[root];
  if (pitchClass === undefined) throw new Error(`Unsupported pitch root: ${root}`);
  return (octave + 1) * 12 + pitchClass;
}

function midiToPitch(midi: number): string {
  const pc = ((midi % 12) + 12) % 12;
  const octave = Math.floor(midi / 12) - 1;
  return `${sharpNames[pc]}${octave}`;
}

function parseRange(range: string): [number, number] {
  const [low, high] = range.split("-");
  return [pitchToMidi(low), pitchToMidi(high)];
}

function pitchToMidi(pitch: string): number {
  const match = pitch.match(/^([A-G](?:#|b)?)(-?\d)$/);
  if (!match) throw new Error(`Unsupported pitch: ${pitch}`);
  const pc = pitchClasses[match[1]];
  if (pc === undefined) throw new Error(`Unsupported pitch: ${pitch}`);
  return (Number(match[2]) + 1) * 12 + pc;
}

function placeInRange(midi: number, low: number, high: number): number {
  let placed = midi;
  while (placed < low) placed += 12;
  while (placed > high) placed -= 12;
  return placed;
}

function approachPitch(currentRoot: number, nextRoot: number): number {
  const currentClass = ((currentRoot % 12) + 12) % 12;
  const nextClass = ((nextRoot % 12) + 12) % 12;
  const up = (nextClass - currentClass + 12) % 12;
  return up <= 6 ? nextRoot - 1 : nextRoot + 1;
}

function toBeats(value: string | number, measures: number): number {
  if (typeof value === "number") return value;
  if (/^\d+:\d+(:\d+)?$/.test(value)) {
    const [measureText, beatText, tickText] = value.split(":");
    return (Number(measureText) - 1) * measures + (Number(beatText) - 1) + (tickText ? Number(tickText) / 960 : 0);
  }
  return durationToBeats(value, measures);
}

function durationToBeats(value: string | number, measures: number): number {
  if (typeof value === "number") return value;
  const match = value.match(/^(\d+(?:\.\d+)?)(m|n|t)$/);
  if (!match) return 0;
  const amount = Number(match[1]);
  if (match[2] === "m") return amount * measures;
  if (match[2] === "t") return amount / 3;
  return (4 / amount) * measures / 4;
}

function beatsToTime(beat: number, measures: number): string {
  const safeBeat = Math.max(0, beat);
  const measure = Math.floor(safeBeat / measures) + 1;
  const inMeasure = safeBeat - (measure - 1) * measures;
  const beatNumber = Math.floor(inMeasure) + 1;
  const tick = Math.round((inMeasure - Math.floor(inMeasure)) * 960);
  return tick > 0 ? `${measure}:${beatNumber}:${tick}` : `${measure}:${beatNumber}`;
}

function beatsToDuration(beats: number, measures: number): string | number {
  if (Math.abs(beats - measures) < 0.001) return "1m";
  if (Math.abs(beats - measures * 2) < 0.001) return "2m";
  if (Math.abs(beats - 2) < 0.001) return "2n";
  if (Math.abs(beats - 1) < 0.001) return "4n";
  if (Math.abs(beats - 0.5) < 0.001) return "8n";
  return Math.max(0.25, beats);
}

function beatsPerMeasure(timeSignature: string): number {
  return Number(timeSignature.split("/")[0] ?? 4);
}

function sectionLift(index: number): number {
  return (index % 4) / 3;
}

function defaultInstrument(role: z.infer<typeof partSchema>["role"]): InstrumentName {
  if (role === "drums") return "drum_kit";
  if (role === "bass") return "upright_bass";
  if (role === "harmony") return "electric_piano";
  if (role === "lead") return "solo_cello";
  if (role === "counterline") return "analog_lead";
  return "glass_pad";
}

function titleFromId(id: string): string {
  return id
    .split(/[-_]+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join(" ");
}

function dumpYaml(value: unknown): string {
  return yaml.dump(prune(value), { lineWidth: 120, noRefs: true, sortKeys: false });
}

function prune<T>(value: T): T {
  if (Array.isArray(value)) return value.map(prune).filter((item) => item !== undefined) as T;
  if (!value || typeof value !== "object") return value;
  const out: Record<string, unknown> = {};
  for (const [key, item] of Object.entries(value)) {
    const next = prune(item);
    if (next === undefined) continue;
    if (Array.isArray(next) && next.length === 0) continue;
    if (typeof next === "object" && next && !Array.isArray(next) && Object.keys(next).length === 0) continue;
    out[key] = next;
  }
  return out as T;
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}
